# Generated by Django 5.2.13 on 2026-04-21 04:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalReputationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('license_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('reason', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reputation_reports', to='management.agency')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('cin_hash', 'license_hash', 'reported_by')},
            },
        ),
    ]
